language: python
python:
  - 3.6
install:
  - pip install -r requirements.txt
  - pip install pytest==3.5.1 pytest-sugar==0.9.1 pytest-pep8==1.0.6 pytest-cov==2.5.1 pytest-asyncio==0.8.0
  - pip install coveralls==1.3.0
script:
  py.test tests --doctest-modules --pep8 -v --cov-report term-missing --cov=hackernews
  py.test hackernews --pep8
after_success:
  coveralls